# nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx
namespace: monitoring
spec:
replicas: 2
selector:
  matchLabels:
    app: nginx
template:
  metadata:
    labels:
      app: nginx
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "80"
      prometheus.io/path: "/metrics"
  spec:
    containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80