apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: monitoring
resources:
  - namespaces/monitoring.yaml
  - configmaps/prometheus-config.yaml
  - configmaps/grafana-datasource.yaml
  - deployments/prometheus.yaml
  - deployments/grafana.yaml
  - services/prometheus-service.yaml
  - services/grafana-service.yaml